export const Auth = {
  USERNAME_CHANGED: 'auth/USERNAME_CHANGED',
  USERNAME_INCORRECT: 'auth/USERNAME_INCORRECT',
  PASSWORD_CHANGED: 'auth/PASSWORD_CHANGED',
  PASSWORD_INCORRECT: 'auth/PASSWORD_INCORRECT',
  LOGIN_USER_SUCCESS: 'auth/LOGIN_USER_SUCCESS',
  LOGIN_USER_FAIL: 'auth/LOGIN_USER_FAIL',
  USER_LOADED: 'auth/USER_LOADED',

  LOGIN_MODAL_POPUP: 'auth/LOGIN_MODAL_POPUP',
  LOGIN_MODAL_HIDE: 'auth/LOGIN_MODAL_HIDE',
};
